const T = [
    "NEVER INSTALL A MOD YOU DON'T TRUST. IT WILL HAVE FULL SYSTEM ACCESS.",
    "THE CUSTOM NIGHT IS IN THE EXTRAS MENU.",
    "YOU WILL EVENTUALLY BE ABLE TO PLAY THIS GAME IN VIRTUAL REALITY.",
    "TIP: ANIMATRONICS GET MORE AGGRESSIVE AS THE NIGHT GOES ON.",
    "TIP: NIGHTS ARE 9 MINUTES LONG.",
    "TIP: TYPE MOD TO ACCESS THE MOD LOADER MENU",
]